# Generated by Django 5.0.6 on 2024-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_gender_sale_product_gender_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='images/brands/'),
        ),
    ]
